version: "2"

services:
  dremio:
    restart: always
    image: dezota/dremio-oss:2.0.5
    hostname: dremio
    volumes:
      - ./dremio.conf:/opt/dremio/conf/dremio.conf:ro
      - ./dremio-env:/opt/dremio/conf/dremio-env:ro
#      - ./certs:/etc/certs:ro
      - dremio_data:/var/lib/dremio
    ports:
      - "9047:9047"   # UI (HTTP)
      - "31010:31010" # ODBC/JDBC clients
      - "2181:2181"   # ZooKeeper
      - "45678:45678" # Inter-node communication

volumes:
  dremio_data:
  